### PR TITLE
Dependencies - Update

### PR DESCRIPTION
**Pull request by 0xbase12**
**Project**
- updated dependencies

**CI** 
- publish project version number to SonarQube
- run on `self-hosted` runner to speed up the build process (Azure is too slow)
- use `lein-test-report-sonar` plugin and publish unit test resutls to SonarQube

### CODE REVIEW

**Comment by 0xbase12** [comment]
I didn't updated kafka libraries. Because I don't know what it implies when changing them regarding the deployed kafka server. If you want to update them go ahead.

**Comment by konstan** [comment]
@0xbase12 Yes, I saw you reverted the update of Kafka libs. No problem. I will check it.

**Comment by konstan** [comment]
The issue is there irrespective of using `cloverage` or tunning tests directly (`lein cloverage --codecov` and `lein test`).

**Comment by konstan** [comment]
@0xbase12 in principal the PR can be merged modulo the fact that we are testing on ES 7.0.0 node. 

```
$ lein deps :tree 2>&1 | grep elastic
[org.elasticsearch.test/framework "7.0.0" :exclusions [com.carrotsearch.randomizedtesting/randomizedtesting-runner]] -> [commons-logging "1.1.3"]
[org.elasticsearch.client/transport "7.0.0"] -> [org.elasticsearch/elasticsearch "7.0.0"] -> [joda-time "2.10.1"]
[org.elasticsearch.test/framework "7.0.0" :exclusions [com.carrotsearch.randomizedtesting/randomizedtesting-runner]] -> [org.elasticsearch/elasticsearch "7.0.0"] -> [joda-time "2.10.1"]
[org.elasticsearch.client/transport "7.0.0" :exclusions [joda-time]]
[org.elasticsearch.test/framework "7.0.0" :exclusions [joda-time com.carrotsearch.randomizedtesting/randomizedtesting-runner]]
   [org.elasticsearch.client/elasticsearch-rest-client-sniffer "7.12.1" :exclusions [[com.fasterxml.jackson.core/jackson-core]]]
   [org.elasticsearch.client/elasticsearch-rest-client "7.12.1"]
 [org.elasticsearch.client/transport "7.0.0" :scope "test"]
   [org.elasticsearch.plugin/lang-mustache-client "7.0.0" :scope "test"]
   [org.elasticsearch.plugin/parent-join-client "7.0.0" :scope "test"]
   [org.elasticsearch.plugin/percolator-client "7.0.0" :scope "test"]
   [org.elasticsearch.plugin/rank-eval-client "7.0.0" :scope "test"]
   [org.elasticsearch.plugin/reindex-client "7.0.0" :scope "test"]
     [org.elasticsearch/elasticsearch-ssl-config "7.0.0" :scope "test"]
   [org.elasticsearch.plugin/transport-netty4-client "7.0.0" :scope "test"]
$
```

I recall you mentioning you bumped up the ES libs version on `parent`. Did you push the change already?
Otherwise, I can open PR on `parent` for ES libs 7.11.1. Let me know. 
I tested with ES 7.11.1 libs on my side and all worked fine.

**Comment by 0xbase12** [comment]
Yes thanks @konstan, tried to change ES version but I got some timeouts during testing. 
Will have to investigate that later on. Will add a ticket for that.

**Pull request merged**
