### PR TITLE
Pull mode

### PR DESCRIPTION
**Pull request by cjdcordeiro**
fixes https://github.com/nuvla/api-server/issues/412
fixes https://github.com/nuvla/api-server/issues/430
fixes https://github.com/nuvla/api-server/issues/429

This should also serve as input for https://github.com/nuvla/ui/issues/495

needs https://github.com/nuvla/job-engine/pull/148

### CODE REVIEW

**Comment by 0xbase12** [comment]
I think you forgot to implement the state "WAITING"

**Comment by cjdcordeiro** [comment]
I don't think it is needed after all: https://github.com/nuvla/api-server/issues/412#issuecomment-740024484

**Comment by 0xbase12** [comment]
So we go with QUEUED and execution mode to make the difference

**Comment by cjdcordeiro** [comment]
yep, I think that's enough...no need to introduce a new state given that we have `execution-mode`. Do you see it differently?

**Comment by 0xbase12** [comment]
I want to rewrite the version description: it's not enough clear "schema version". 
What about: Compatibility indicator which represent Job-engine major version

**Pull request closed without merging**
