### PR TITLE
Nuvlabox status - Update heartbeat even if NuvlaBox encounter a spec …

### LINKED ISSUE #527: Nuvlabox heartbeat should be set even if spec validation fail
Nuvlabox agent send telemetry at a regular interval. The edit of telemetry by a NB make the server set the next-heartbeat attribute. The telemetry data are sent as discovered by the NB and is complex. It may happen that a spec issue happen and make fail the edit. In this case, the api-server should edit the next-heartbeat to inform that the nuvlabox was there even if the edit failed.

### PR DESCRIPTION
**Pull request by 0xbase12**
…validation issue

Fixes #527

### CODE REVIEW

**Review by cjdcordeiro — COMMENTED** [review]
won't this be a problem for migrations?

i.e. if I, wither by mistake or because a migration went wrong, install NB Engine v2, using NB Engine v1's compose files...the schemas will always fail to match, and in reality, the NB should be unusable. But in this case, we give the impression it is online...

Is this a problem?

apart from this comment, the PR lgtm

**Comment by konstan** [comment]
My take on this heartbeat is - the patient may have a problem with her brain, but her heart still beats. So, she is "online".

Another metric would be "health", which following that exception can already be set to "yellow". Not sure we have such a metric yet. Should we create one?

**Comment by 0xbase12** [comment]
There is already 2 attribute in nuvlabox-status that fits there:
- status - #{"OPERATIONAL" "DEGRADED" "UNKNOWN"}
- status-notes - Previously called 'comment', now turned into a list of notes related with the status

An enhancement on NB agent, is to detect spec issue when pushing telemetry and move status to DEGRADED and add a status-notes on that.

**Comment by cjdcordeiro** [comment]
we could indeed detect the spec issue on the agent, but you're still relying on a server-side attribute (2 actually: status and status-notes). 

Anyway, this could be discussed on a separate thread. feel free to merge

**Pull request merged**
