### PR TITLE
nuvlabox resources

### PR DESCRIPTION
**Pull request by loomis**
This PR contains the port of the resources related to NuvlaBox management.

### CODE REVIEW

**Comment by loomis** [comment]
The initial commits to this PR contain a "brute force" migration of the SlipStream NuvlaBox resources to Nuvla. The resources and associated tests have been updated to conform to the resource naming conventions and to remove features from tests that aren't supported (yet). Although the code builds and passes all of the tests, **this PR must not be merged until the schemas and workflows have been finalized.**

"Mechanical" updates:

 - [ ] Review the resource schemas and ensure that all attributes have kebab-case names.
 - [ ] Decide which resources need to be versioned (probably at a minimum the "record" resource) and update the implementations/schemas to allow this versioning.
 - [ ] Do the schemas need to different depending on the NuvlaBox type (standard, nano, etc.)?
 - [ ] Determine if the "record" schema should be templated.  (That is, does the "create" schema need to be different from the "core" schema of the resource.)

Workflow/relationship decisions:

 - [ ] Do we continue to support NuvlaBox identifiers?  These were used for "regular" NuvlaBox machines but not nanos. Using them requires (obviously) an extra resource, but also complicates keeping a consistent "state" of resources for a NuvlaBox.
 - [ ] For SlipStream, a dedicated SlipStream user was created for each NuvlaBox. Is this still desired or is it enough to use the "account" of the owner with appropriate API key/secret creds? New ACLs may help here as any identifier can be used as a principal name; it doesn't have to be a user (or group). 
 - [ ] What "state" do we keep about the boxes? What entity/account/resource is responsible for this? 
 - [ ] Do we keep a history of the state?  Currently there is a resource that does this, using the same technique as the old SlipStream monitoring.  Nuvla does not have this subsystem.  Do we need to bring it back, give up state history, come up with an alternate implementation, etc.?
 - [ ] Presumably dynamic device information will be provided by the NuvlaBox to Nuvla. Is this included in the state resource, record resource, another resource? 
 - [ ] What is the relationship with the VPN server? Currently there are callouts to an API that isn't part of Nuvla. Must this be brought in (now, later, never)? If it is used, do we move certificate management to the server (as has been discussed in the past) or leave this to be done elsewhere. If elsewhere, what are the backup strategies for maintaining state?  Now that we're using containers, would it be easier to have a separate VPN server per client? 
 - [ ] In SlipStream, there was a field that linked the NuvlaBox and a connector.  Is this the same link between a NuvlaBox and an infrastructure-service-group (ISG) and infrastructure-service?  Is there a 1-to-1 relationship between a NuvlaBox and an ISG? 
 - [ ] How does the state information interact with the notification resource? What features are required by the NuvlaBox for the notification resource?

**Comment by cjdcordeiro** [comment]
mt 2 cents:

>  Decide which resources need to be versioned (probably at a minimum the "record" resource) and update the implementations/schemas to allow this versioning.

`state` as well I think

---

> Do the schemas need to different depending on the NuvlaBox type (standard, nano, etc.)?

No. They might depend however on whether it is just a NuvlaBox Engine or a full NuvlaBox OS. For the latter we can provide more information.

---

> Determine if the "record" schema should be templated. (That is, does the "create" schema need to be different from the "core" schema of the resource.)

Don't see why.

---

>  Do we continue to support NuvlaBox identifiers? These were used for "regular" NuvlaBox machines but not nanos. Using them requires (obviously) an extra resource, but also complicates keeping a consistent "state" of resources for a NuvlaBox.

we do use them for the Nano, but not as an ID. They are unique for each NuvlaBox though. 

---

>  Presumably dynamic device information will be provided by the NuvlaBox to Nuvla. Is this included in the state resource, record resource, another resource?

The NB dynamically populates `record`, `state`, and `credential`

---

> What is the relationship with the VPN server? Currently there are callouts to an API that isn't part of Nuvla. Must this be brought in (now, later, never)? If it is used, do we move certificate management to the server (as has been discussed in the past) or leave this to be done elsewhere. If elsewhere, what are the backup strategies for maintaining state? Now that we're using containers, would it be easier to have a separate VPN server per client?

This is needed. The VPN API should probably be re-furbished though? A VPN server per client, do you mean user? 

---

>In SlipStream, there was a field that linked the NuvlaBox and a connector. Is this the same link between a NuvlaBox and an infrastructure-service-group (ISG) and infrastructure-service? Is there a 1-to-1 relationship between a NuvlaBox and an ISG?

yes. The `activate` operation is creating a connector. This should be changed so that the `activate` operations creates an ISG instead

---

**Comment by loomis** [comment]
Updated list of changes based on the above feedback and the discussion between the developers:

"Mechanical" updates:

 - [ ] Ensure that all attributes have kebab-case names.
 - [ ] Remove references to quotas.
 - [ ] Change implementation to allow for versioned nuvlabox-record schema.
 - [ ] Change implementation to allow for versioned nuvlabox-state schema.

 - A single schema will be used for all NuvlaBox flavors.
 - There is no need for the nuvlabox-record or the nuvlabox-state to be templated resources.

Workflow/relationship decisions:

 - [ ] Remove the nuvlabox-identifier resource and references to it. The nuvlabox-record id will be the immutable identifier for a given NuvlaBox.
 - [ ] Remove the nuvlabox-state-snapshot resource. State history will not be kept by the server.
 - [ ] Remove the creation of a dedicated user for each NuvlaBox. 
 - [ ] Change the nuvlabox-state ACL to allow each NuvlaBox to update its own state.
 - [ ] Update the nuvlabox-state schema to have two categories of information: peripheral data and resource data.  These two categories may, at a later time, be split into two resources.
 - [ ] Create an infrastructure-service-group resource for each NuvlaBox.
 - [ ] Create infrastructure-service resources (Swarm, Minio) with the ISG for each NuvlaBox.

 - NuvlaBox access to resources will be controlled by either a group identifier or the nuvlabox-record id. How the correct claim ends up in the authentication token must be determined. 
 - The server will contain only the instantaneous state of NuvlaBox machines. If history of a NuvlaBox is desired, then this must be provided by an external service.
 - A decision about how to deal with the relationship between the NuvlaBox resources and the VPN has been postponed. For the moment, the VPN references will be removed.

**Comment by loomis** [comment]
Work related to notifications are in a separate ticket (#146) that should be scheduled when the notification resource has been merged.

**Comment by loomis** [comment]
Points requiring more work:

- Decide how to create infrastructure-service resources (Swarm, Minio) with the ISG for each NuvlaBox.  Either the activate action will have to take parameters to pass this information on to the service creation calls or the NuvlaBox itself will have to create those resources directly.
 - NuvlaBox access to resources will be controlled by either a group identifier or the nuvlabox-record id. How the correct claim ends up in the authentication token must be determined. 
 - Currently the nuvlabox-record id is used in the ACL to allow the NuvlaBox to modify the nuvlabox-record. The full authentication workflow must be understood so that the correct claims can be added to any created sessions.

**Comment by cjdcordeiro** [comment]
can you also add the following nuvlabox-state attrs:
 - ip (for the IP that should be used for the endpoint when building the infrastructure service)
 - state-log (optionally to explain why a box is in a state)

name them as you prefer

**Comment by loomis** [comment]
> state-log (optionally to explain why a box is in a state)

The only state that looks like it would need an explanation is the "QUARANTINED" state.  It seems like the existing "comment" field would be appropriate to use for this. No?

> ip (for the IP that should be used for the endpoint when building the infrastructure service)

I don't think that is appropriate for the `nuvlabox-record`. Either this should be a parameter passed to the activate action, which will then create the ISG and IS resources, or the NuvlaBox itself should create the ISG and IS resources directly. I would slightly prefer the second option, as this doesn't require version-specific code for the activate action, if the collection of services on the NuvlaBox changes (e.g. we switch from Swarm to K8S, add Minio, etc.).

**Comment by cjdcordeiro** [comment]
> > state-log (optionally to explain why a box is in a state)
> 
> The only state that looks like it would need an explanation is the "QUARANTINED" state. It seems like the existing "comment" field would be appropriate to use for this. No?

you're thinking about the `-record` resource and not the `-state` one. In `-state` we have `#{"NEW" "ONLINE" "OFFLINE" "UNKNOWN"}` (btw, "NEW" should be removed from here cause it won't ever happen inside `-state`). This "operational" state can change and is used for the notifications implemented by Lionel. The names are confusing and should probably be reviewed. 

Nevertheless, yes we could have a field like `comment` in `-state` as well. 

> 
> > ip (for the IP that should be used for the endpoint when building the infrastructure service)
> 
> I don't think that is appropriate for the `nuvlabox-record`. Either this should be a parameter passed to the activate action, which will then create the ISG and IS resources, or the NuvlaBox itself should create the ISG and IS resources directly. I would slightly prefer the second option, as this doesn't require version-specific code for the activate action, if the collection of services on the NuvlaBox changes (e.g. we switch from Swarm to K8S, add Minio, etc.).

Should we be passing attrs to a public POST operation? Nevertheless that would not work because the IP changes with time and we cannot activate more than once.

The second option would work yes...but just adds more complexity to the NuvlaBox and cause maintenance headaches everytime we change the ISG on the server. I'd rather keep the NB as simple and decoupled as possible. 

Anyway, having the IP in the NuvlaBox categorization doesn't seem unreasonable to be. It is not an endpoint, but simply an IP. It is a characteristic of the device. 

Please let me know asap which one to implement here

**Comment by cjdcordeiro** [comment]
requests:
 - [ ] move mac-address from mandatory to optional
 - [ ] remove "NEW" from the nuvlabox-state. If the state is created it's because the activation was performed (hopefully from within the NuvlaBox), thus it is ONLINE
 - [ ] when a nuvlabox-record is deleted, the respective ISG remains with nb record ID as parent. This should probably be removed
 - [ ] (**IMPORTANT**) some sort of credential must be passed back during the activation, otherwise the NB does not have the rights to update the nb resources
 - [ ] the `state` in both the `nuvlabox-record` and `nuvlabox-state` are confusing. These should either converge into one of the resources or be renamed

**Comment by cjdcordeiro** [comment]
plus:
 - [ ] on nb record delete, also delete all the associated resources: apikey credential, ISG, state and IS
 - [ ] add `swarm-manager-token` and `swarm-worker-token` to the schema

**Comment by cjdcordeiro** [comment]
don't forget to:
 - [ ] when either `ip` or `vpn-ip` are available in the `nuvlabox-state`, an IS should be created (give preference to `vpn-ip`)
 - [ ] when an IS is created, the respective docker swarm credential must also be created, based of the TLS keys which are published into the `nuvlabox-state`
 - [ ] the attributes for the TLS certificates must be added to `nuvlabox-state` so the Nuvlabox can update them

All this could be done by the NB directly, but I believe that's a bad practice because if the server changes in the future, we'll need to update all NuvlaBoxes. 

This way, the NuvlaBox only relies on the `nuvlabox-record` and `nuvlabox-state`, which makes sense.

**Comment by loomis** [comment]
The following changes were made in the commit 7eb5dc4. 

> move mac-address from mandatory to optional

This has been done, but it begs the question, is the mac-address needed at all?  It is no longer used as an identifier for the NuvlaBox. If it is needed, is one mac-address enough, i.e. will any NuvlaBox have more than one active network interface? Can the mac-address change (use of different NIC, replacement of hardware, ...)? If so, perhaps this should move to nuvlabox-state rather than nuvlabox-record. 

> remove "NEW" from the nuvlabox-state. If the state is created it's because the activation was performed (hopefully from within the NuvlaBox), thus it is ONLINE

The "NEW" status has been removed; however, the initial status will be "UNKNOWN", as the status isn't valid until the NuvlaBox actually updates the nuvlabox-state resource directly. 

>  the state in both the nuvlabox-record and nuvlabox-state are confusing. These should either converge into one of the resources or be renamed

The "state" attribute in nuvlabox-state has been renamed to "status", as this field indicates the current status of the NuvlaBox, as opposed to the formal lifecycle state given in the nuvlabox-record.  Given that the information in the nuvlabox-state globally is really the current status information, perhaps the resource as a whole should be renamed from "nuvlabox-state" to "nuvlabox-status".

**Comment by loomis** [comment]
> on nb record delete, also delete all the associated resources: apikey credential, ISG, state and IS

Performing a global clean-up of resources associated with a NuvlaBox will certainly facilitate the management of the NuvlaBox resources.  However, I view this as an all-or-nothing task.  So the full list of resources to be deleted would be:

 - nuvlabox-record
 - nuvlabox-state
 - associated API key/secret (which will need to have "parent" set)
 - the infrastructure-service-group associated to the nuvlabox-record (again parent must be set)
 - all infrastructure-service resources within the infrastructure-service-group (the group cannot be deleted while it contains services)
 - all deployments related to those services must be stopped and then deleted
 - all credentials tied to those services must be deleted 

Given that this cannot be a synchronous action with the stoppage of the deployments, the nuvlabox-record delete action will have to create a job and return the job id and an accepted (202) status. This will also require an additional state in the nuvlabox-record lifecycle to mark it as being in the process of being deleted ("DELETING"?). This state must be propagated to the infrastructure-service resources to prevent new workloads from starting.

If there's agreement on the above list and the behavior, it can be implemented.

**Comment by loomis** [comment]
> All this could be done by the NB directly, but I believe that's a bad practice because if the server changes in the future, we'll need to update all NuvlaBoxes.

I have very mixed feelings about this request. While I understand the concern about having the NuvlaBox depend only on the nuvlabox-* versioned resources, I also don't want the nuvlabox-state to become a dumping ground for attributes that are better stored in other resources. For example, the tokens and TLS certificates are more logically credentials. Duplicating this information opens up issues with coherence between the values, while putting them in the nuvlabox-state leads to a catch-all resources with no clear function. I think that this needs discussion before being implemented.

**Comment by cjdcordeiro** [comment]
> This has been done, but it begs the question, is the mac-address needed at all?

I don't think it is. But this was not yet widely discussed among us all 

> The "NEW" status has been removed; however, the initial status will be "UNKNOWN", as the status isn't valid until the NuvlaBox actually updates the nuvlabox-state resource directly.

yep

> The "state" attribute in nuvlabox-state has been renamed to "status", as this field indicates the current status of the NuvlaBox, as opposed to the formal lifecycle state given in the nuvlabox-record. Given that the information in the nuvlabox-state globally is really the current status information, perhaps the resource as a whole should be renamed from "nuvlabox-state" to "nuvlabox-status".

makes sense. I'll update the attribute name in the agent. Let me know if the resource name is also changed

> So the full list of resources to be deleted would be: (...)

yep I agree with it all. I'm just wondering about the feasibility of deleting all the IS within that ISG...what if you have an IS which is not being provided by the NuvlaBox but it is in the same ISG?

**Comment by loomis** [comment]
The conclusions from a discussion between @schaubl @0xbase12 @loomis and @cjdcordeiro were the following:

 - rename nuvlabox-state to nuvlabox-status
 - this resource should have "state" renamed to "status" and the allowed values are "OPERATIONAL", "DEGRADED", and "UNKNOWN".
 - deleting the nuvlabox-record will delete all associated resources from an asynchronous job
 - the delete will change the ACLs on the nuvlabox-record/-status to disallow updates except from admin and set the nuvlabox-record state to DECOMMISSIONING synchronously
 - two new states for the nuvlabox-record lifecycle will be added: "DECOMMISSIONING" and "ERROR"
 - the "ERROR" state will be for a clean up job that fails
 - a new action "RECOMMISSION" will be added that takes credential information from the NuvlaBox and creates the associated infrastructure-service and credential resources
 - a credential will need to be added for the swarm tokens

For those who participated in the meeting, please correct the above points or add ones that I've missed. Comments welcome from anyone.

**Comment by mebster** [comment]
What are the corresponding statuses to:
- lost connection (unreachable or no network)
- partial hardware or software failure
- failing connected peripherals 

If we upgrade a NB, is there a special status to apply during this phase?

**Comment by cjdcordeiro** [comment]
those are not defined yet, as we do not have the procedures to detect them. However, the `status` and `state` fields are well defined lists of strings, which can be modified at any time without breaking any of the already deployed software. 

> lost connection (unreachable or no network)
this cannot be set from the NB, and the `notification` resource is not being migrated at this point. Most likely this will again become a watch job setting the `status` to 'UNREACHABLE' (or something similar)

> partial hardware or software failure
that's "degraded"

> failing connected peripherals
not sure this is even related with the NuvlaBox. We will categorize peripherals. The ones we cannot categorized (like the ones failing), are not going to be put into Nuvla, thus no need to trigger an error for something we don't see
If the problem however is about using those peripherals, then it becomes somehow also related with `deployment`...so this requires some extra thought

**Comment by mebster** [comment]
Great. For your last point, yes we need to explore this a bit more. Basically it comes from the experience of loosing incoming video stream of sensor events, which come via devices detected and reported in the nuvlabox-status. But it’s not a show stopper.

**Comment by loomis** [comment]
The core features have all been implemented; however, before final merge the following implementations need to be improved for production:

 1. The 'recommission' action must handle missing fields reasonably and be able to update existing resources.
 1. The nuvlabox delete job must be extended to clean up all the deployment, data-object, and data-record resources.

**Comment by loomis** [comment]
Merging to allow easier debugging of the remaining tasks: 1) finalizing/fixing the NuvlaBox registration and 2) allowing updates of resources on the "recommission" action.

**Pull request merged**
