### PR TITLE
Credential template/exoscale

### PR DESCRIPTION
**Pull request by cjdcordeiro**

### CODE REVIEW

**Comment by cjdcordeiro** [comment]
> Those credentials are typically generic

in fact they are not, at least when it comes to docker-machine, thus the cloud-specific templates. 

The problem is that for each driver, we'll need a different set of attributes. Example:

**GCE**: (https://github.com/nuvla/api-server/pull/50) you'll need a private key and several identification parameters. These constitute a service account credential (in GCE's terms) and are to be used all together 

**Exoscale**: (this PR) just needs (as you correctly stated) the generic API key and secret

**Azure**: in addition of the client ID and secret (analogy with API key), one needs the subscription ID

> I would not like to see the user have to create separate credential resources for machine, S3, etc. when they simply duplicate the same information.

we wouldn't duplicate, because after all these credentials can also be used for S3 and other cloud resources

> I also think that information not strictly linked to the credential should be put elsewhere. The logical place for parameters tied to machine would be in the (infrastructure-)service template, rather than the credential.

agreed, but for now these PRs are only about the credentials for the respective clouds

> works well for 1 or 2 clouds before trying to extend this to all the supported clouds.

agreed. The plan was to only have Exo, AWS, Azure and GCE for now. Then once validated we would add others like DigitalOcean, Rackspace, Openstack (which is a bit more complex) etc.

---

So if I got your comment right, I'd agree that the main issue here is that we are creating N credential types for N clouds. I don't think it influences the user experience. On the other hand, it generates more code to maintain on our side. 

The alternative is to keep the old `credential-template-cloud` system, but this is the one I think would make things harder for us and the users. Reasons:
 - dynamic metadata loading: if we keep this generic, it will be impossible to instruct users on which cloud attributes we are actually looking for, i.e., if we have cloud-specific credentials, we can explicitly name and tag the attributes after their real cloud-given denomination, and load this information both on the user side (UI) and on our side (connectors) without having to hardcode schemas
 - relative complements between different cloud credentials: as exemplified above, the programmatic authentication mechanisms might differ from cloud to cloud, adding, excluding, or even completely altering the mandatory credential set. If we keep a single generic `credential-template-cloud`, how do we take into account cloud-specific mandatory credential attributes?

**Comment by loomis** [comment]
> So if I got your comment right, I'd agree that the main issue here is that we are creating N credential types for N clouds. I don't think it influences the user experience. On the other hand, it generates more code to maintain on our side.

No, the 1 credential per cloud doesn't bother me. The thing I want to avoid is having 1 credential per service per cloud.  As long as the user can specify one credential and tie it to all appropriate services, I'm OK with that.  The cloud credentials are not the same across clouds and I expect that the schemas will vary by cloud but not (normally) by service. 

When reusing credentials between services, the choice of using the machine credential schema will clearly simplify the implementation of the machine binding.  However, this will also likely complicate the implementations of anything else that uses those credentials (e.g. the external object that will use those credentials for S3).  That's unavoidable; we just need to recognize that a choice of convenience for machine will mean more work on other implementations.

**Comment by cjdcordeiro** [comment]
> The thing I want to avoid is having 1 credential per service per cloud

that's not the case. (well depends how u define a `service`...but that's another discussion), but no, the same credential should be good for N docker-machines, N s3 endpoints, etc...


> However, this will also likely complicate the implementations of anything else that uses those credentials (e.g. the external object that will use those credentials for S3). That's unavoidable

yes, absolutely true...it's just about finding a compromise somewhere. I've used the default docker-machine terminology cause it is very explicit (user friendly) and I'd imagine it will be the most used kind of service

**Comment by cjdcordeiro** [comment]
but if you don't see any issues on this then please merge

**Comment by loomis** [comment]
> but if you don't see any issues on this then please merge

The schemas should be built on the infrastructure-service-credential to pick up the reference to the infrastructure-services.   I think a couple of the constants at the top are not used. Also it would be good to use the standard formatting of the files.  The merge conflicts need to be fixed as well.

**Comment by cjdcordeiro** [comment]
- unused constants removed
 - conflicts fixed
 - formatted

but the other comment I'm not sure how to address. This credential must exist before any infrastructure/service is created.

**Comment by loomis** [comment]
> but the other comment I'm not sure how to address. This credential must exist before any infrastructure/service is created.

The credential would reference the service it uses, not the one it creates.  This supposes that we create infrastructure-service resources for the Exoscale, AWS, etc. compute services. To avoid requiring this, I've changed the service credential schema to allow zero infrastructure-service resources to be referenced by the credential. In any case, if these credentials are to be used for other services, there must be a possibility to reference those services in the schema.

**Comment by cjdcordeiro** [comment]
> The credential would reference the service it uses, not the one it creates

it should be the created service who references the credential which was used to create it. It's the same analogy as with our current `deployment` schema

The credential must exist before any service (expect for imported ones)

**Pull request merged**
